name = "GenomicDiversity"
uuid = "594eec9e-a086-4631-8fc7-61104af37930"
authors = ["Darren Irwin <irwin@zoology.ubc.ca>"]
version = "0.2.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"

[compat]
julia = "1"
CairoMakie = "0.12"
MultivariateStats = "0.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
